# Generated by Django 2.2.13 on 2021-06-10 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20210611_0151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='photo_1',
            new_name='photo_balcony',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='photo_2',
            new_name='photo_bathroom',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='photo_3',
            new_name='photo_bedroom',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='photo_4',
            new_name='photo_kitchen',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='photo_5',
            new_name='photo_sitting_room',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='photo_6',
            new_name='photo_toilet',
        ),
    ]
